@startchen Entertaiment
left to right direction

entity Users {
}
entity Categories <<weak>> {
}
entity Activities {
}

relationship Created_Cat {
}
Created_Cat -(1,1)- Users
Created_Cat -(0,N)- Categories

relationship Created_Act {
}
Created_Act -(1,1)- Users
Created_Act -(0,N)- Activities

relationship Do {
}
Do -(0,N)- Users
Do -(0,N)- Activities

relationship Categorized {
}
Categorized -(1,1)- Categories
Categorized -(1,N)- Activities

@endchen